// Autogenerated by jnigen. DO NOT EDIT!

#include <stdint.h>
#include "dartjni.h"
#include "jni.h"

thread_local JNIEnv* jniEnv;
JniContext* jni;

JniContext* (*context_getter)(void);
JNIEnv* (*env_getter)(void);

void setJniGetters(JniContext* (*cg)(void), JNIEnv* (*eg)(void)) {
  context_getter = cg;
  env_getter = eg;
}

// com.monsieurmahjong.commonjong.api.ShantenCalculation
jclass _c_ShantenCalculation = NULL;

jmethodID _m_ShantenCalculation__new0 = NULL;
FFI_PLUGIN_EXPORT
JniResult ShantenCalculation__new0() {
  load_env();
  load_class_global_ref(
      &_c_ShantenCalculation,
      "com/monsieurmahjong/commonjong/api/ShantenCalculation");
  if (_c_ShantenCalculation == NULL)
    return (JniResult){.value = {.j = 0}, .exception = check_exception()};
  load_method(_c_ShantenCalculation, &_m_ShantenCalculation__new0, "<init>",
              "()V");
  if (_m_ShantenCalculation__new0 == NULL)
    return (JniResult){.value = {.j = 0}, .exception = check_exception()};
  jobject _result = (*jniEnv)->NewObject(jniEnv, _c_ShantenCalculation,
                                         _m_ShantenCalculation__new0);
  return to_global_ref_result(_result);
}

jmethodID _m_ShantenCalculation__countShanten = NULL;
FFI_PLUGIN_EXPORT
JniResult ShantenCalculation__countShanten(jobject string) {
  load_env();
  load_class_global_ref(
      &_c_ShantenCalculation,
      "com/monsieurmahjong/commonjong/api/ShantenCalculation");
  if (_c_ShantenCalculation == NULL)
    return (JniResult){.value = {.j = 0}, .exception = check_exception()};
  load_static_method(_c_ShantenCalculation,
                     &_m_ShantenCalculation__countShanten, "countShanten",
                     "(Ljava/lang/String;)I");
  if (_m_ShantenCalculation__countShanten == NULL)
    return (JniResult){.value = {.j = 0}, .exception = check_exception()};
  int32_t _result = (*jniEnv)->CallStaticIntMethod(
      jniEnv, _c_ShantenCalculation, _m_ShantenCalculation__countShanten,
      string);
  return (JniResult){.value = {.i = _result}, .exception = check_exception()};
}
