// Autogenerated by jnigen. DO NOT EDIT!

// ignore_for_file: annotate_overrides
// ignore_for_file: camel_case_extensions
// ignore_for_file: camel_case_types
// ignore_for_file: constant_identifier_names
// ignore_for_file: file_names
// ignore_for_file: lines_longer_than_80_chars
// ignore_for_file: no_leading_underscores_for_local_identifiers
// ignore_for_file: non_constant_identifier_names
// ignore_for_file: overridden_fields
// ignore_for_file: unnecessary_cast
// ignore_for_file: unused_element
// ignore_for_file: unused_field
// ignore_for_file: unused_import
// ignore_for_file: unused_local_variable
// ignore_for_file: unused_shown_name

import "dart:isolate" show ReceivePort;
import "dart:ffi" as ffi;
import "package:jni/internal_helpers_for_jnigen.dart";
import "package:jni/jni.dart" as jni;

// Auto-generated initialization code.

final ffi.Pointer<T> Function<T extends ffi.NativeType>(String sym) jniLookup =
    ProtectedJniExtensions.initGeneratedLibrary("mahjong-engine");

/// from: com.monsieurmahjong.commonjong.api.ShantenCalculation
class ShantenCalculation extends jni.JObject {
  @override
  late final jni.JObjType<ShantenCalculation> $type = type;

  ShantenCalculation.fromRef(
    jni.JObjectPtr ref,
  ) : super.fromRef(ref);

  /// The type which includes information such as the signature of this class.
  static const type = $ShantenCalculationType();
  static final _new0 = jniLookup<ffi.NativeFunction<jni.JniResult Function()>>(
          "ShantenCalculation__new0")
      .asFunction<jni.JniResult Function()>();

  /// from: public void <init>()
  /// The returned object must be released after use, by calling the [release] method.
  factory ShantenCalculation() {
    return ShantenCalculation.fromRef(_new0().object);
  }

  static final _countShanten = jniLookup<
              ffi
              .NativeFunction<jni.JniResult Function(ffi.Pointer<ffi.Void>)>>(
          "ShantenCalculation__countShanten")
      .asFunction<jni.JniResult Function(ffi.Pointer<ffi.Void>)>();

  /// from: static public int countShanten(java.lang.String string)
  static int countShanten(
    jni.JString string,
  ) {
    return _countShanten(string.reference).integer;
  }
}

final class $ShantenCalculationType extends jni.JObjType<ShantenCalculation> {
  const $ShantenCalculationType();

  @override
  String get signature =>
      r"Lcom/monsieurmahjong/commonjong/api/ShantenCalculation;";

  @override
  ShantenCalculation fromRef(jni.JObjectPtr ref) =>
      ShantenCalculation.fromRef(ref);

  @override
  jni.JObjType get superType => const jni.JObjectType();

  @override
  final superCount = 1;

  @override
  int get hashCode => ($ShantenCalculationType).hashCode;

  @override
  bool operator ==(Object other) {
    return other.runtimeType == ($ShantenCalculationType) &&
        other is $ShantenCalculationType;
  }
}
