// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package raw

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Community struct {
	CommunityID int32
	Name        string
	CreatedBy   string
	Description pgtype.Text
	CreatedAt   pgtype.Timestamp
	UpdatedAt   pgtype.Timestamp
}

type CommunityMember struct {
	CommunityID int32
	Username    string
	Role        string
}

type OriginalPhoto struct {
	PhotoID    uuid.UUID
	Username   string
	Path       string
	UploadedAt pgtype.Timestamp
	IsPublic   bool
	UpdatedAt  pgtype.Timestamp
}

type TransformedPhoto struct {
	PhotoID    uuid.UUID
	Username   string
	OutputType string
	Path       string
	UploadedAt pgtype.Timestamp
}

type User struct {
	Username  string
	Email     string
	Nickname  string
	IsDeleted bool
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}
