#name: Backend Workflow
#
#on:
#  push:
#    branches: [ "main" ]
#  pull_request:
#    paths:
#      - "backend/**"
#      - "!backend/**.md"
#jobs:
#
#  test:
#    runs-on: ${{ matrix.os }}
#    defaults:
#      run:
#        working-directory: ./backend
#
#    strategy:
#      matrix:
#        os: [ ubuntu-latest, macos-latest, windows-latest ]
#        architecture: [ "x64", "arm64" ]
#        python-version: [ "3.11" ]
#        exclude:
#          - os: ubuntu-latest
#            architecture: arm64
#          - os: windows-latest
#            architecture: arm64
#
#    steps:
#      - uses: actions/checkout@v3
#
#      - name: Setup Python
#        uses: actions/setup-python@v4
#        with:
#          architecture: ${{ matrix.architecture }}
#          python-version: ${{ matrix.python-version }}
#
#      - name: Backend tests
#        run: make ci-test
#
#  build:
#    runs-on: ubuntu-latest
#
#    permissions:
#      id-token: write   # This is required for requesting the JWT
#      contents: read    # This is required for actions/checkout
#
#    steps:
#      - uses: actions/checkout@v3
#
#      - name: Set up QEMU
#        uses: docker/setup-qemu-action@v3
#      - name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v3
#
#      - name: Configure AWS credentials
#        uses: aws-actions/configure-aws-credentials@v4
#        with:
#          role-to-assume: arn:aws:iam::654654581568:role/cheshire-backend-github-action-role
#          aws-region: us-east-1
#
#      - name: Build, tag, and push docker image to Amazon ECR
#        env:
#          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
#          REPOSITORY: cheshire-backend
#          IMAGE_TAG: ${{ github.sha }}
#        run: |
#          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG -t $REGISTRY/$REPOSITORY:latest .
#          docker push $REGISTRY/$REPOSITORY:IMAGE_TAG --all-tags
