name: Photo Transformer Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    paths:
      - "src/python/**"
      - "!**.md"

jobs:

  test:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: ./src/python

    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        architecture: [ "x64", "arm64" ]
        python-version: [ "3.11" ]
        exclude:
          - os: ubuntu-latest
            architecture: arm64
          - os: windows-latest
            architecture: arm64

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          architecture: ${{ matrix.architecture }}
          python-version: ${{ matrix.python-version }}

      - name: tests
        run: make tests

  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src/python

    permissions:
      id-token: write   # This is required for requesting the JWT
      contents: read    # This is required for actions/checkout

    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::654654581568:role/photo-transformer-github-action-role
          role-session-name: photo-transformer-workflow-session
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          mask-password: 'false'

      - name: Build and tag Docker image
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: photo-transformer
          IMAGE_TAG: ${{ github.sha }}
        run: make build && make release
